# Generated by Django 5.2 on 2025-10-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_guestuser_alter_cart_user_cart_guest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='guest_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
