# Generated by Django 5.2 on 2025-08-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (e.g., 10 for 10% off)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_text',
            field=models.CharField(blank=True, help_text="Custom discount text (e.g., 'Limited Time Offer')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image (thumbnail)', null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of image display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
