# Generated by Django 5.2 on 2025-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perfume', 'Perfume'), ('shirt', 'Shirt'), ('car', 'Car'), ('mobile_accessories', 'Mobile Accessories')], default='perfume', max_length=50),
        ),
    ]
