# Generated by Django 5.2 on 2025-11-16 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_percentage_product_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perfume', 'Perfume'), ('clothing', 'Clothing'), ('car', 'Car'), ('mobile_accessories', 'Mobile Accessories'), ('watches', 'Watches')], default='perfume', max_length=50),
        ),
    ]
