# Generated by Django 5.2 on 2026-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perfume', 'Perfume'), ('clothing', 'Clothing'), ('car', 'Car'), ('mobile_accessories', 'Mobile Accessories'), ('watches', 'Watches'), ('bridal', 'Bridal')], default='perfume', max_length=50),
        ),
    ]
