# Generated by Django 5.2 on 2025-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_featuredproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newly_added',
            field=models.BooleanField(default=False),
        ),
    ]
