# Generated by Django 5.2 on 2025-07-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_best_seller_product_newly_added_and_more'),
        ('products', '0008_product_rating'),
    ]

    operations = [
    ]
