version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  # PostgreSQL Database (only for production)
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - production

  # Redis for caching (optional, for production)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    profiles:
      - production

volumes:
  postgres_data: 