# Generated by Django 5.2 on 2025-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='whtsapp_image',
            field=models.ImageField(blank=True, null=True, upload_to='whtsapp_images/'),
        ),
    ]
